import { STATUSES } from "./status";

// Sample data - each product with separate ID and status
export const initialProducts = [
    {
        id: 1,
        productName: "Web Application",
        runId: 1,
        runName: "Web Application Run",
        cicdType: "CI/CD",
        subModule: "No",
        agentType: "Agent",
        status: STATUSES.SUCCESS,
        startTime: "2024-01-15 10:30:00",
        duration: "2d 34m",
    },
    {
        id: 2,
        productName: "API Service",
        runId: 1,
        runName: "Web Application Run",
        cicdType: "CI/CD",
        subModule: "No",
        agentType: "Agent",
        status: STATUSES.SUCCESS,
        startTime: "2024-01-15 10:32:00",
        duration: "1d 45m",
    },
    {
        id: 3,
        productName: "Mobile App",
        runId: 2,
        runName: "Mobile App Run",
        cicdType: "CI Only",
        subModule: "Yes",
        agentType: "Poller",
        status: STATUSES.RUNNING,
        startTime: "2024-01-15 11:45:00",
        duration: "1d 12m",
    },
    {
        id: 4,
        productName: "Authentication Service",
        runId: 2,
        runName: "Mobile App Run",
        cicdType: "CI Only",
        subModule: "Yes",
        agentType: "Poller",
        status: STATUSES.PENDING,
        startTime: "2024-01-15 11:47:00",
        duration: "0d 0m",
    },
    {
        id: 5,
        productName: "Database",
        runId: 3,
        runName: "Database Run",
        cicdType: "CD Only",
        subModule: "No",
        agentType: "Agent",
        status: STATUSES.FAILED,
        startTime: "2024-01-15 09:15:00",
        duration: "4d 56m",
    },
    {
        id: 6,
        productName: "Microservice A",
        runId: 3,
        runName: "Database Run",
        cicdType: "CD Only",
        subModule: "No",
        agentType: "Agent",
        status: STATUSES.CANCELLED,
        startTime: "2024-01-15 09:17:00",
        duration: "0d 5m",
    },
];


